### ISSUE TITLE
Error running panphlan_map

### ISSUE THREAD

**Issue by sanpande** [SegataLab/panphlan#20]
Hi, Is the tool still being maintained? I get the following error, any idea what is causing it?

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
[I] Bowtie2 is installed
    version: 2.4.2, path: /path_to/panphlan3/bin/bowtie2
[I] Samtools version 1.7;  path: /path_to/panphlan3/bin/samtools
[I] bowtie2 --very-sensitive --no-unal -x ../Escherichia_coli/Escherichia_coli -U /path_to/set1.fastq -p 12 --quiet
[I] Rejected 0 reads over 767680 total
Bowtie2 mapping and SAM filtering completed.
[I] Samtools version 1.7;  path: /path_to/panphlan3/bin/samtools
[I] samtools view -bS /tmp/panphlan_4v2u5r8r.sam
[I] samtools index /tmp/panphlan_d1xyemzq.bam
[I] samtools mpileup /tmp/panphlan_d1xyemzq.bam > /tmp/panphlan_w96kyqix.csv
Traceback (most recent call last):
  File "/path_to/panphlan3/bin/panphlan_map.py", line 397, in <module>
    main()
  File "/path_to/panphlan3/bin/panphlan_map.py", line 391, in main
    genes_abundances(tmp_csv.name, contig2gene, args)
  File "/path_to/panphlan3/bin/panphlan_map.py", line 340, in genes_abundances
    contig, position, abundance = words[0], int(words[1]), int(words[3])
IndexError: list index out of range

Thank you
sp

**Comment by leonarDubois** [comment]
Hello, 

thanks for using PanPhlAn and reporting this issue, it helps improving the software.
The problem here seems to be in reading the samtools mpileup results that are by default written in a tmp file. If your execution of `panphlan_map.py` has been interrupted, then the file might still be present (not erased at the end of the run). Can you check the content of your  `/tmp/panphlan_w96kyqix.csv` ? Looking at it might help a lot to solve the problem.

Otherwise it can also come from the samtools version (I use the 1.10 where you used the 1.7), but actually I would be surprised it this is causing the issue.

Best regards,
Léonard

**Comment by sanpande** [comment]
I see the file. looks like the last row is not complete. 

LYAM01000288.1  37494   N       1       c       F
LYAM01000288.1  37495   N       1       c       F
LYAM01000288.1  37496   N       0       *       *
LYAM01000288.1  37497   N       1       t       F
LYAM01000288.1  37498   N       1       t       F
LYAM01000288.1  37499   N       0       *       *
LYAM01000288.1  37500   N       1       t       F
LYAM01000288.1  37501   N       1       g       F
LYAM01000288.1  37502   N       0       *       *
LYAM01000288.1  37503   N       1       c       F
LYAM01000288.1  37504   N       1       a       F
LYAM01000288.1  37505   N       1       g       8
LYAM01000288.1  37506   N       1       t       8
LYAM01000288.1  37507   N       1       a       F
LYAM01000288.1  37

how can I fix it ?

Thank you.
sp

**Comment by leonarDubois** [comment]
Hello,

I updated PanPhlAn to version 3.1 and fixed the bioconda recipe that shoul solve problem of boztie2 and samtools version

**Comment by bnowinsk** [comment]
Hello Léonard,

Is there potentially an issue with bowtie2 and samtools version needed? I have not found a similar issue reported, this one posted here seems the closest to my issue. 

I installed using conda install -c bioconda panphlan 
This installed bowtie2 2.4.1 , samtools 1.9 and panphlan 3.1 in my panphlan conda environment.

When I run panphlan_map.py, I get the following error, which I'm wondering if is due to the bowtie2 version installed?

STEP 1. Checking software...
/home/user/.conda/envs/panphlan_test/bin/bowtie2-align-s: symbol lookup error: /home/user/.conda/envs/panphlan_test/bin/bowtie2-align-s: undefined symbol: _ZN3tbb10interface78internal15task_arena_base19internal_initializeEv
(ERR): Description of arguments failed!
Exiting now ...
Traceback (most recent call last):
  File "/home/user/.conda/envs/panphlan_test/bin/panphlan_map.py", line 412, in <module>
    main()
  File "/home/user/.conda/envs/panphlan_test/bin/panphlan_map.py", line 393, in main
    check_bowtie2()
  File "/home/user/.conda/envs/panphlan_test/bin/misc.py", line 19, in check_bowtie2
    bowtie2_version = bowtie2_version.communicate()[0].decode('utf-8').split()[2]
IndexError: list index out of range

Thanks,
Brent

**Comment by leonarDubois** [comment]
Hi, 

Indeed the bowtie2 installation seem to have some issue.
It seems that a similar issue occurred here: https://forum.biobakery.org/t/unknown-bowtie2-errors/1871

Tell me if you manage to fix it

**Comment by bnowinsk** [comment]
Thank you for sharing. Downgrading tbb worked using:
conda install tbb=2020.2
