### ISSUE TITLE
panphlan_map.py: Cannot set temporary directory location

### ISSUE THREAD

**Issue by nick-youngblut** [SegataLab/panphlan#22]
`panphlan_map.py` uses `/tmp/` for temporary files, but on a cluster, `/tmp/` is usually not regulated and can fill up with files, which would cause `panphlan_map.py` to die due to a disk usage error. It would be helpful if the user can specify the temporary directory location. 

A general, minor comment about the `panphlan_map.py` help docs:

```
usage: panphlan_map.py [-h] [-i INPUT] [--indexes INDEXES] [-p PANGENOME] [-o OUTPUT] [--bt2 BT2]
                       [-b OUT_BAM] [--nproc NPROC] [--min_read_length MIN_READ_LENGTH]
                       [--th_mismatches TH_MISMATCHES] [-m SAM_MEMORY] [--fasta] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        Metagenomic sample to map
  --indexes INDEXES     Bowtie2 indexes path and file prefix
  -p PANGENOME, --pangenome PANGENOME
                        Path to pangenome tsv file exported from ChocoPhlAn
  -o OUTPUT, --output OUTPUT
                        Path to output file
  --bt2 BT2             Additional bowtie2 mapping options, separated by slash: /-D/20/-R/3/,
                        default: -bt2 /--very-sensitive/
  -b OUT_BAM, --out_bam OUT_BAM
                        Get BAM output file
  --nproc NPROC         Maximum number of processors to use. Default is 12 or a lower number of
                        available processors.
  --min_read_length MIN_READ_LENGTH
                        Minimum read length, default 70
  --th_mismatches TH_MISMATCHES
                        Number of mismatches to filter (bam)
  -m SAM_MEMORY, --sam_memory SAM_MEMORY
                        Maximum amount of memory for Samtools (in Gb). Default 4
  --fasta               Read are fasta format. By default considered as fastq
  -v, --verbose         Show progress information
```

Many of the `optional arguments:` are not optional, and since there are no required arguments set for `argparse`, running `panphlan_map.py` fails instead of printing the help docs. The user cannot determine which of the "optional" arguments are actually required without having to refer to the online panphlan docs. 

Also, there's nothing in the help docs that the output file path will be appended with `.bz2` and the output will be compressed.

**Comment by nick-youngblut** [comment]
This error might be related:

```
2000000 reads; of these:
  2000000 (100.00%) were unpaired; of these:
    1845642 (92.28%) aligned 0 times
    8697 (0.43%) aligned exactly 1 time
    145661 (7.28%) aligned >1 times
7.72% overall alignment rate
samtools sort: couldn't allocate memory for bam_mem
samtools index: "/tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam" is in a format that cannot be usefully indexed
[mpileup] fail to read the header of /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam

STEP 1. Checking software...
[I] Bowtie2 is installed
    version: 2.4.2, path: /ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/bowtie2
[I] Samtools version 1.11;  path: /ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/samtools

STEP 2.  Mapping the reads...
[I] input_path
[I] bowtie2 --very-sensitive --no-unal -x /ebio/abt3_scratch/nyoungblut/LLMGPS_55977766656/panphlan/Bacteroides_vulgatus/Bacteroides_vulgatus -U - -p 4
[I] Created temporary file /tmp/1363950.1.long.q/panphlan_v77f4s92.sam
[W] Please wait. The computation may take several minutes...
[I] SAM records filtering: mismatches threshold is at -1, length threshold is at 70
[I] Rejected 0 reads over 157262 total
Bowtie2 mapping and SAM filtering completed.
[I] Samtools version 1.11;  path: /ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/samtools
[I] samtools view -bS /tmp/1363950.1.long.q/panphlan_v77f4s92.sam
[I] Temporary .bam file has been generated
[I] cmd (v1.11): samtools sort -m 287762808832 - -o /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam
[I] Temporary .bam file /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam has been sorted
[I] User-defined .bam file /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam has been sorted
Samtools SAM->BAM translation (view+sort) completed.

STEP 3. Piling up...
[I] samtools index /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam
[I] BAM file /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam has been indexed
[I] samtools mpileup /tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam > /tmp/1363950.1.long.q/panphlan_ybav7t8v.csv
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/panphlan_map.py", line 397, in <module>
    main()
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/panphlan_map.py", line 387, in main
    piling_up(out_bam, is_tmp, tmp_csv.name, args)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/panphlan_map.py", line 297, in piling_up
    os.unlink(bam_file + '.bai')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/1363950.1.long.q/panphlan_0e7mpnwm.bam.bai'
```

This error occurs when submitting jobs to a compute cluster in which the `/tmp/` directories on each node are quite limited in size.

**Comment by nick-youngblut** [comment]
Changing `os.unlink(bam_file + '.bai')` to `if os.path.isfile(bam_file + '.bai'): os.unlink(bam_file + '.bai')` fixes the issue, but why doesn't the .bai file persistent until the `os.unlink()`?...

I can submit a PR, if you'd like.

**Comment by nick-youngblut** [comment]
Actually, the issue is due not checking on the bam-indexing subprocess:

```
    try:
        # command: samtools index <INPUT BAM FILE>
        index_cmd = ['samtools', 'index', bam_file]
        print('[I] ' + ' '.join(index_cmd))
        p4 = subprocess.Popen(index_cmd)
        if args.verbose: print('[I] BAM file ' + bam_file + ' has been indexed')
        try:
            with open(csv_file, mode='w') as ocsv:
```

...so if the command dies, the python script continues. For instance, changing that code to:

```
    try:
        # command: samtools index <INPUT BAM FILE>
        index_cmd = ['samtools', 'indeX_THIS_WILL_FAIL', bam_file]
        print('[I] ' + ' '.join(index_cmd))
        p4 = subprocess.Popen(index_cmd)
        if args.verbose: print('[I] BAM file ' + bam_file + ' has been indexed')
        try:
            with open(csv_file, mode='w') as ocsv:
```

generates the following successful run with an empty output `csv.bz2` file:

```
STEP 1. Checking software...
[I] Bowtie2 is installed
    version: 2.4.2, path: /ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/bowtie2
[I] Samtools version 1.11;  path: /ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/samtools

STEP 2.  Mapping the reads...
[I] input_path
[I] bowtie2 --very-sensitive --no-unal -x Eubacterium_rectale/Eubacterium_rectale -U - -p 8
[I] Created temporary file /tmp/panphlan_my6svgzl.sam
[W] Please wait. The computation may take several minutes...
[I] SAM records filtering: mismatches threshold is at -1, length threshold is at 70
2000000 reads; of these:
  2000000 (100.00%) were unpaired; of these:
    1959365 (97.97%) aligned 0 times
    11006 (0.55%) aligned exactly 1 time
    29629 (1.48%) aligned >1 times
2.03% overall alignment rate
[I] Rejected 0 reads over 41579 total
Bowtie2 mapping and SAM filtering completed.
[I] Samtools version 1.11;  path: /ebio/abt3_projects/software/dev/ll_pipelines/llmgps/.snakemake/conda/d291232a/bin/samtools
[I] samtools view -bS /tmp/panphlan_my6svgzl.sam
[I] Temporary .bam file has been generated
[I] cmd (v1.11): samtools sort -m 67645734912 - -o /tmp/panphlan_ngga99zs.bam
[I] Temporary .bam file /tmp/panphlan_ngga99zs.bam has been sorted
[I] User-defined .bam file /tmp/panphlan_ngga99zs.bam has been sorted
Samtools SAM->BAM translation (view+sort) completed.

STEP 3. Piling up...
[I] samtools indeX_THIS_WILL_FAIL /tmp/panphlan_ngga99zs.bam
[I] BAM file /tmp/panphlan_ngga99zs.bam has been indexed
[I] samtools mpileup /tmp/panphlan_ngga99zs.bam > /tmp/panphlan_whj15ark.csv
[main] unrecognized command 'indeX_THIS_WILL_FAIL'
[mpileup] 1 samples in 1 input files
Samtools piling up (view+mpileup) completed.

STEP 4. Exporting results...
Dictionary for {contig:{gene:(from,to)}} has been created.
[W] Please wait. The computation may take several minutes...
```

...so if the bam indexing fails due to lack of memory, lack of space in /tmp/, or any other reason, `panphlan_map.py` will continue. 

The `except (KeyboardInterrupt, SystemExit):` construct for that section makes it hard to include a:

```
p4.wait()
if p4.returncode != 0:
    sys.exit('[E] Samtools encountered some error.\n')
```

since that will just trigger the `except (KeyboardInterrupt, SystemExit):` error of `sys.exit('[E] Execution has been manually halted.\n')` even though it's a system error, not a keyboard interrupt error.

**Comment by nick-youngblut** [comment]
Also, the `isTemp` variable is undefined

**Comment by nick-youngblut** [comment]
After modifying the code to get the STDOUT/STDERR of `p4`, I found out that the indexing is dying due to: 

```
samtools index: "/tmp/1364310.1.long.q/panphlan_kboq9ko5.bam" is in a format that cannot be usefully indexed
```

This is not a memory issue, given that I've used up to 250G of memory with no success.
