### ISSUE TITLE
Lactobacillus case and Lactobacillus paracasei

### ISSUE THREAD

**Issue by qinglong89** [SegataLab/panphlan#28]
Hi, why there are no pre-built pangenomes for Lactobacillus case and Lactobacillus paracasei?

Is than possible you can generate those two and upload them online?

Thanks.

**Comment by leonarDubois** [comment]
Hello,

we generated the database of pangenomes using what was available on RefSeq. Some species having only one reference genome available are available in MetaPhlAn or StrainPhlAn but were discarded for PanPhlAn as its use will be extremely limited (a pangenome based on one genome would be irrelevant).

If you have at least 2 references genomes available, I advised you to use the [PanPhlAn_pangenome_exporter](https://github.com/SegataLab/PanPhlAn_pangenome_exporter) that is less user friendly than PanPhlAn but allows to generate some custom pangenomes

Hope this will help you profile your species

**Comment by qinglong89** [comment]
Thank you.
Testing the exporter scripts now, but receiving the error in the final writing step:

#########################################################################################
Tue Feb 23 11:45:04 2021 Writing PanPhlAn tsv...Traceback (most recent call last):
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 520, in <module>
    panphlan_exporter(args.input, args.tmp, args.output, args.clade_name, args.nprocs, args.db_path)
  File "../PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 501, in panphlan_exporter
    write_panphlan_tsv(inputdir, tmp_dir, ppa_outdir, clade_name, contigs_names_dict, contigs_names_dict_prokka, extend_pangenome)
  File "../PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 425, in write_panphlan_tsv
    for rec in GFF.parse(gff_file, limit_info=dict(gff_type = ['CDS'])):
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 746, in parse
    target_lines):
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 51, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given

#####################################################################################

Any comment for modifying "/home/qinglong/Programs/biobakery3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py"?

**Comment by qinglong89** [comment]
Could be a solution?
https://www.biostars.org/p/449931/
