### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: False

### ISSUE THREAD

**Issue by zckoo007** [SegataLab/panphlan#3]
Hi , thanks for developing this great tool!

I have been studying panphlan example

I download 14 fna and put them into reference_genomes/
```
GCA_000209935.fna
GCA_000209955.fna
GCA_001404855.fna
GCA_001405295.fna
GCA_001406375.fna
GCA_001406835.fna
GCA_003122495.fna
GCA_003436035.fna
GCA_003436785.fna
GCA_003438175.fna
GCA_003438365.fna
GCA_003438715.fna
GCA_003438925.fna
GCA_003438965.fna
```
when I run the follwing code I get an error，would you please give `panphlan_39491_pangenome.csv` file?
```
./panphlan/panphlan_new_pangenome_generation.py \
	-c 39491 --i_fna reference_genomes/ -o . --verbose

(panphlan) [ckzhu@vm-login02 panphlan]$ ./panphlan/panphlan_new_pangenome_generation.py \
> -c 39491 --i_fna reference_genomes/ -o . --verbose

 Error: Pangenome file (reference_genomes/panphlan_39491_pangenome.csv) not found
```

I also try old code
```
(panphlan) [ckzhu@vm-login02 panphlan]$ ./panphlan/panphlan_pangenome_generation.py -c 39491 --i_fna reference_genomes/ -o . --verbose

PanPhlAn pangenome generation version 1.2.3.7
Python version: 3.7.3
System: linux
./panphlan/panphlan_pangenome_generation.py -c 39491 --i_fna reference_genomes/ -o . --verbose

[I] Input genome FNA folder: /public/home/sample_lib/ckzhu/software/panphlan/reference_genomes/
[I] Species database name: 39491
[I] Identity threshold percentage: 95.0 %.
[I] Output folder: ./
[I] Temporary folder: TMP_panphlan_db/

STEP 1. Checking required software installations ...
[I] Bowtie2 is installed, version: 2.4.1, path: /public/home/sample_lib/ckzhu/miniconda3/envs/panphlan/bin/bowtie2
[I] Usearch v.7 is installed, version: v7.0.1090_i86linux32, path: /public/home/sample_lib/ckzhu/software/panphlan/usearch7

STEP 2. Prepare input gene and genome files ...
Traceback (most recent call last):
  File "./panphlan/panphlan_pangenome_generation.py", line 1341, in <module>
    main()
  File "./panphlan/panphlan_pangenome_generation.py", line 1294, in main
    path_genome_fna_files, path_gene_ffn_files = check_genomes(args['i_ffn'], args['i_fna'], VERBOSE)
  File "./panphlan/panphlan_pangenome_generation.py", line 1089, in check_genomes
    genefiles   = [f for f in os.listdir(ffn_folder) if fnmatch(f,'*.'+FFN)]
NotADirectoryError: [Errno 20] Not a directory: False

```
 Is there something else I need to download?

**Comment by leonarDubois** [comment]
Hello ! 

sorry for the late reply. You'll find the pangenome file attached
[panphlan_39491_pangenome.csv.zip](https://github.com/SegataLab/panphlan/files/4608755/panphlan_39491_pangenome.csv.zip)
The error while running the pangenome generation code comes from the file format expected. (FASTA files with .ffn extension). The current version is not very flexible about it.

We are actually working on a new version of PanPhlAn that should come out soon and aims to be more flexible about these file extensions while also easily providing all the files needed in a convenient way.

Thanks for your patience, and let me know if some things are still unclear.
