### ISSUE TITLE
sample below MIN COVERAGE

### ISSUE THREAD

**Issue by namdeka** [SegataLab/panphlan#35]
I get this error after the step 3 (strain presence/absence) during profiling when I try a different threshold. It was working the first time I tried it. What can be the issue? I used: 

python panphlan/panphlan_profiling.py --min_coverage 1 --left_max 0.70 --right_min 0.30 -i map_results_P_gingivalis -p Porphyromonas_gingivalis/Porphyromonas_gingivalis/Porphyromonas_gingivalis_pangenome.tsv --o_matrix result_profile_gingivalis0.1.tsv --add_ref --o_covplot gingivalis_covplotnew0.1 --verbose

Traceback (most recent call last):
  File "panphlan/panphlan_profiling.py", line 948, in <module>
    main()
  File "panphlan/panphlan_profiling.py", line 901, in main
    plot_dna_coverage(norm_samples_coverages, sample_stats, avg_genome_length, args, normalized = True)
  File "panphlan/panphlan_profiling.py", line 532, in plot_dna_coverage
    savefig(plot_name, dpi = 300)
  File "/user/ndeka/anaconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/user/ndeka/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/user/ndeka/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2150, in print_figure
    canvas = self._get_output_canvas(backend, format)
  File "/user/ndeka/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2079, in _get_output_canvas
    raise ValueError(
ValueError: Format '1' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)

**Comment by leonarDubois** [comment]
Hello,

it seems that the value passed to the ` --o_covplot` argument makes the matplotlib function crashing as it contains a point and no extension.

Try the same line but with `--o_covplot gingivalis_covplotnew0_1.jpg` instead of  `--o_covplot gingivalis_covplotnew0.1`
